# Generated by Django 2.2.1 on 2024-11-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20241101_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
